### ISSUE TITLE
Divine icon is distorted

### ISSUE THREAD

**Issue by vvs** [exile-center/better-trading#114]
![Screenshot 2022-09-21 171348](https://user-images.githubusercontent.com/9781/191542843-1584e829-fa67-4620-bd42-50b6c75ff73c.png)
Latest Chrome, Windows 10

**Comment by dbjorge** [comment]
Thanks for reporting the issue! 751494540a5a621d39f868bd51149dcdecedb172 resolves this; the fix will be included in the next release.

**Comment by dbjorge** [comment]
Fix released in 1.7.1.
