### ISSUE TITLE
Playstation | Filters not persisted when registering trade

### ISSUE THREAD

**Issue by lesse83** [exile-center/better-trading#117]
Hi,
first of all thanks for this amazing addon and the effort you put in.

I'm able to use the extension for the PC version of poe without flaws - however when I'm trying to register the trades for my playstation account (PS5) nothing is persisted (not the search field nor any filters).

Example:
If I store a filter by filling out the fields and registering it:
![save](https://user-images.githubusercontent.com/114808564/193406197-a199a3c9-0817-4dc4-bcae-2f5fc2d3a56d.png)

... and then double click the registered item, the fields are empty.
![load](https://user-images.githubusercontent.com/114808564/193406238-0f654310-ce22-49fa-b33b-7588e427c39f.png)

Thanks again for your great work!

**Comment by pboutin** [comment]
The way it work, it saves the current URL of the browser (which should change every time a new search is triggered). Make sure the URL properly updates within the browser before saving a trade.

**Comment by lesse83** [comment]
Ok - the url gets updated after klicking search - for example:
https://www.pathofexile.com/trade/search/sony/Kalandra/WmwDL4mSm

...if i then register the trade, afterwards double click the registered trade the last parameter of the resulting URL is stripped: https://www.pathofexile.com/trade/search/sony/Kalandra

(like said - it works for PC, but not for Playstation...)

**Comment by dbjorge** [comment]
Hi @lesse83,

Thanks for reporting the issue! I confirm that I can reproduce the issue you've described, I'll take a look at fixing it tonight.

**Comment by dbjorge** [comment]
This is fixed by https://github.com/exile-center/better-trading/commit/817525b13e8a03d3fc1257d89ca31ec17d042537 and will be included in the next version of the extension.

**Comment by dbjorge** [comment]
Fix released in 1.7.1.

**Comment by lesse83** [comment]
Awesome - thanks a lot!
