### ISSUE TITLE
pin function not showing

### ISSUE THREAD

**Issue by buqieryu0** [exile-center/better-trading#127]
![image](https://user-images.githubusercontent.com/121281619/209290094-59fb3ef4-35cb-4467-9b09-5af4d71466c8.png)
Somehow the pin button doesn't show in the website layout.

I am using winedge, not chrome. Not sure whether this is a issue.

**Comment by dbjorge** [comment]
Hi @buqieryu0, thanks for reporting the issue! I don't think Edge vs Chrome is likely to be the issue; I verified that the "Pin" button shows up in Edge on my machine.

It looks like you may have another extension that is also modifying this section of the trade site - neither the "December 15, 2022 at 4:45 PM EST" text underneath the "listed 7 days ago" line nor the "Report" button appear in the default trade site experience, and neither is added by this extension. If you're using some other extension that's adding these, it's likely that it's responsible for breaking the "Pin" button. Do you know what is adding those?

**Comment by buqieryu0** [comment]
@dbjorge  hi,thanks for the respond. I am also using the TFT Trade Extension which has similar function with better trading. The pic is attack at bottom. The "Report" button is from that. Maybe two extensions modified the same section. But after I disabled both of extensions, and reboot the better trading, the "Pin" button still not appear where it should be. I have a snapshot here.
![image](https://user-images.githubusercontent.com/121281619/209450046-edbb6b04-0bd6-4fa4-87aa-32a4de07757a.png)
Right in the mid between "Whisper" and "Ignore" is still empty. Hope the info could help to fix this.

By the way, better trading is so cool. Lots of details which other programs don't have is so convenience. Like Arranging and one button for live search. Just saying without exaggeration, Better Trading with these details make my life much easier. Great work and thanks a lot.
Just one thing, sometimes I feel the row line for each row is a little bit width. I have too much item need search.  So I hope those should fit in one screen. I don't need to scroll down. If users can adjust it, it would be better. TFT trade extension has a compact button which could make all rows skinny.

And last is the snapshot for tft ext.
![image](https://user-images.githubusercontent.com/121281619/209449752-c74cb2ad-d182-405c-8ed4-929dbab5e292.png)

**Comment by pboutin** [comment]
TFT's extension point is to mimic the behaviours of this extension, having both at the same time might always be an issue as they reimplement some of our features in their project.

@dbjorge it would be possible to adapt, but I have the feeling this would be an endless cat and mouse game.

**Comment by buqieryu0** [comment]
@pboutin You are right. I remove both extensions and reinstalled both. The problem solved. It seems when I have both extensions, one is preventing update of the other one. After several versions, finally problems occurred.
