### ISSUE TITLE
Afflcition - returning palyer

### ISSUE THREAD

**Issue by S1lverone** [exile-center/better-trading#140]
I returned to poe this league affliction. i went to pathofeciel trade site and wanted to buy my stuff, but all. i mean everything. is gone. i have 0 bookmarks. what have happened?

**Comment by pboutin** [comment]
Bookmarks data is stored locally in your browser. So a lot of things may have happened:
- Cleared your local storage
- Reinstalled your browser
- Changed computer
- etc..
