### ISSUE TITLE
Recover Data from SSD?

### ISSUE THREAD

**Issue by FeralRage7** [exile-center/better-trading#149]
Hello,

My old computer wouldn't boot so I built a new one. I have access to the old SSD. Is there any way to recover the Better Trading saved folders from there?

Thanks,
FeralRage7

**Comment by pboutin** [comment]
The bookmarks are persisted in the browser's LocalStorage. You could check ressources online to check how to restore Chrome user data from an external hard drive.

**Comment by FeralRage7** [comment]
@pboutin Any idea where Better Trading stores these files? I don't want to copy / paste the entire directory. I'd like to be more surgical, if possible. Thanks for the reply!

**Comment by pboutin** [comment]
BetterTrading doesn't store any files, Chrome does. It would be along with the official poe trading site user data.

**Comment by FeralRage7** [comment]
@pboutin sorry, any other resources you can point me to? I had several builds and I know it's on me for not exporting the file but I wasn't expecting my computer to crash. I would love to dig it out of whatever nook it's stored in in Chrome. How does the trade website user data store the saved searches from BetterTrading? Where can I access these files?

**Comment by FeralRage7** [comment]
@pboutin fellow [redditor](https://www.reddit.com/r/pathofexile/comments/18980mu/better_trading_poe_help/) saved the day. The files are stored under C:\Users\[USER]\AppData\Local\Google\Chrome\User Data\Default\Extensions\fhlinfpmdlijegjlpgedcmglkakaghnk\1.7.2_0. Replacing that folder from my old hard drive brought back all my saved trades. Hopefully this helps someone else!
