### ISSUE TITLE
Similar function broken

### ISSUE THREAD

**Issue by theveug** [exile-center/better-trading#151]
Account group borken after the new # added to account names. so the "Similar" function doesnt work right now.

**Comment by Irfy** [comment]
It's not just that it doesn't work properly, it groups items from unrelated accounts. The only temporary workaround is to disable grouping in settings (info icon top-right).

**Comment by dbjorge** [comment]
Fixed by 18dbecd9be439e6cfde4b74408b1d37ef2c029a1, will be in 1.8.0 release
