### ISSUE TITLE
PoE2 support

### ISSUE THREAD

**Issue by Larlenn** [exile-center/better-trading#152]
Hi
love the extension
any chance for PoE2 support any time soon, now that poe2 trade is up?

Thank you very much

**Comment by Byngalo** [comment]
Yes, please poe2 support

**Comment by Fleymour** [comment]
yeah hope too!

**Comment by Gisbert12843** [comment]
second that

**Comment by bjbeare** [comment]
Yes, please!

**Comment by MonsterQinging** [comment]
hope so , i love this.

**Comment by MDLeide** [comment]
Voicing my support for a PoE2 patch

**Comment by DTBScale** [comment]
Please

**Comment by reruem** [comment]
plzzzzzzzz

**Comment by LyubomirMaksimov** [comment]
Please make it work 🙏

**Comment by MvPGEO** [comment]
Need this for POE 2

**Comment by ELepianka1** [comment]
wtb poe 2 support. love this extension

**Comment by ravenlok** [comment]
Yes, please.

**Comment by dbjorge** [comment]
Thanks for your interest, everyone! Initial support is implemented and will be released as version 1.8.0 of the extension as soon as it gets through all of Google's Chrome Web Store review process.

**Comment by gbrandyb** [comment]
Patreon?

**Comment by dbjorge** [comment]
> Patreon?

I appreciate the thought, but would prefer to keep this project a hobby without money involved. I'd love if you would instead donate whatever amount you might have contributed to your local animal shelter.

**Comment by dbjorge** [comment]
Released in 1.8.0
