### ISSUE TITLE
Doesn't work with PoE 2's trade site

### ISSUE THREAD

**Issue by JasonCweb** [exile-center/better-trading#153]
Do you plan to add support for PoE 2?

**Comment by dbjorge** [comment]
Initial PoE 2 support was released 2 days ago in version 1.8.0. Open chrome://extensions/ and check which version you're using (try the "Update" button on that page if it's not 1.8.0).

If you still have trouble getting it to work with PoE 2 trade after verifying that you're on version 1.8.0+, please feel free to file a new issue with the specific version you're using and the specific URL you're visiting that isn't showing the extension UI.
