### ISSUE TITLE
Make it available on Firefox

### ISSUE THREAD

**Issue by pboutin** [exile-center/better-trading#18]

**Comment by pboutin** [comment]
I tried to make it boot in firefox for the past hour and I really don't know how it's not working. The JS code behind works well (the equivalent pricings shows up and all), but the side-panel remains empty. It's like the app is not able to render anything.

I'm trying to start a conversation on Ember's Discord in order to find a clue...

Unfortunately, it wont make it on time for Delirium 😭

**Comment by z0w13** [comment]
How would I set it up for testing in Firefox, I'm decently experienced in Javascript but not so much in setting something up as a firefox extension

**Comment by pboutin** [comment]
Just a quick heads up, I'm now able to boot the extension in Firefox 🎉 , but the wrapper for the database (Dexie.js) doesn't work.

I opened [a ticket](https://github.com/dfahlander/Dexie.js/issues/999) for their project to see if I can get around it.

Else, I will try to find another wrapper that will work for both chrome and firefox, I will keep you guys posted.

**Comment by pboutin** [comment]
After pushing the investigation deeper, turns out Dexie somehow conflicts with something present on the trade site itself.

The solution would be to replace Dexie with something else and rewrite [the wrapper](https://github.com/exile-center/better-trading/blob/master/app/services/dexie.ts).

Since I'm really no expert with the IndexedDB API, and the chrome version actually get more traction than I expected, I will focus on improvements and features for the chrome version.

------------------------

That being said, if someone wants to try something, here's the step to actually make the extension to boot on Firefox:

### Fix templates rendering

In the `/dist/dev/ember-build/assets/vendor.js`, replace:
```
// check if window exists and actually is the global
var hasDom = typeof self === 'object' && self !== null && self.Object === Object && typeof Window !== 'undefined' && self.constructor === Window && typeof document === 'object' && document !== null && self.document === document && typeof location === 'object' && location !== null && self.location === location && typeof history === 'object' && history !== null && self.history === history && typeof navigator === 'object' && navigator !== null && self.navigator === navigator && typeof navigator.userAgent === 'string';
```
with
```
// check if window exists and actually is the global
var hasDom = true;
```

This is a check performed by ember's internals and it somehow fails when booting in Firefox's extension environment, but since it's a browser extension, we don't need to validate the presence of a browser.

### Fix extension API crash

There's a few places in the code where `chrome.runtime` is invoked, simply replace those with `browser.runtime`. (`window.chrome.runtime` should become `browser.runtime` since `window.browser` breaks in Firefox).

------------------------

Once the database works, it will be simple to have a script to automatically patch the tweaks mentioned above in order to bundle for Firefox.

**Comment by frandarre** [comment]
Sorry to bother you @pboutin. I see you've closed this issue as done. May I know how to add the extension to firefox?

**Comment by pboutin** [comment]
I've refactored the faulty code so it works on Firefox, but it is not yet published (nor fully tested). I plan to release the new version ~1 week before the next league.

Meanwhile, you can checkout the `dev` branch and try running it locally.

**Comment by frandarre** [comment]
Just FYI, I had some issues compiling and didn't manage to get it working at all.

I'll wait patiently for your official release by next league. Thanks for your hard work!
