### ISSUE TITLE
Localize the texts

### ISSUE THREAD

**Issue by pboutin** [exile-center/better-trading#35]
It would be nice to localize the extension's texts.

- applied in the application/route

**Comment by frandarre** [comment]
Any way we can help with translation? I'm a spanish speaking native and I could help with that.

Do you just need an `es.yaml` file in each `translation/` folder?

**Comment by pboutin** [comment]
I was wondering if that feature could be useful or not, since the extension only works on the "english" version of the trading site for now. Thoughts ?

**Comment by frandarre** [comment]
Most of the Spanish/Portuguese speakers I know play with the game in English, so I'd say that a really small subset of people would use the feature.

I guess you'd be fine dropping this feature.

**Comment by pboutin** [comment]
That's what I thought, I'll close this for now to avoid confusion. Thanks for the help proposal :)
