### ISSUE TITLE
Feature suggestion

### ISSUE THREAD

**Issue by Mar-vo** [exile-center/better-trading#42]
It would be cool if there was a button to quickly export search parameters from a search your list, like https://poe-query.now.sh/ does. That would mean you can set aside the parameters, in case a search url expires and restore them. 

Maybe the new incoming export function could export the parameters as well. Perhaps this is just something that would be useful only to me, but i would like it :)

**Comment by pboutin** [comment]
I never encountered a search URL that expires personally, is this really a thing?

Also, the trades that you bookmark are not scoped to a particular league, which means you can reuse the same trades in a future league.

I'm just wondering what's the use of having the whole parameters map when the search identifier works the same?

**Comment by Mar-vo** [comment]
It mostly cool to have a back-up that is safe from being removed :)

**Comment by pboutin** [comment]
Closing as this is not actually a problem (I was able to open up a search I did from the Synthesis league and it worked).

Also, having to fetch the whole config, and saving it would lead to several challenges.
