### ISSUE TITLE
New version changes layout of bulk trade

### ISSUE THREAD

**Issue by joca-bt** [exile-center/better-trading#44]
Old version or plugin disabled:
<img width="1198" alt="before" src="https://user-images.githubusercontent.com/1297942/84591866-07ca6280-ae42-11ea-84a1-00edc7a1ea72.png">

New version of the plugin enabled:
<img width="1175" alt="after" src="https://user-images.githubusercontent.com/1297942/84591868-0ac55300-ae42-11ea-8442-0ae9d6c04bea.png">

The new version is changing the layout and wasting a lot of space. I personally have to disable it to use bulk trade.

**Comment by pboutin** [comment]
Oh you're right, I'ill fix that later today. Thanks for reporting it !

**Comment by pboutin** [comment]
Had a few minutes this morning, I published the fix under version 1.2.4 on both chrome and firefox.
