### ISSUE TITLE
Regrouping identical item/price/seller results together

### ISSUE THREAD

**Issue by livejamie** [exile-center/better-trading#58]
It would be nice if Better Trading could figure out if there are multiple items from a seller and display that somewhere on the listing.

Conservatory Map - 10c [6 other from User]

and if you clicked on the 6 other it let you send a whisper to buy all.

Something like that.

**Comment by livejamie** [comment]
Poe Trade Enhancer does something similar but doesn't allow you to send a whisper to buy all.

![image](https://user-images.githubusercontent.com/49513/85961130-27db4500-b95d-11ea-98aa-075b7ebb54aa.png)

**Comment by pboutin** [comment]
Regrouping identical items/price/seller would be a great idea. Thanks for the feedback !
