### ISSUE TITLE
Whitelisting or Blacklisting results by Item Category or Item Base

### ISSUE THREAD

**Issue by emartinezgh** [exile-center/better-trading#62]
This is a shortcoming of the official site that could probably be fixed by BT.
When you are looking at Staves in particular if you do "Any Staff" it includes Warstaves into the results but mod wise Staves and Warstaves are pretty different. It would be nice to be able to blacklist for that one search any Warstaff or perhaps you want to blacklist the regular Staves and only keep Warstaves.

Same deal when you want to look at multiple bases but don't want to have a search open per base, You could do a base category search and then whitelist or blacklist the specific bases you're not interested in.

Short of having a search per base it doesn't seem like it can be done in a single page on the official site without assistance from an extension, which is where Better Trading comes in.

**Comment by pboutin** [comment]
You can already search for a specific base by searching for its name, [example](https://www.pathofexile.com/trade/search/Harvest/NppWT0)

I don't know if it's what you're looking for ?

**Comment by emartinezgh** [comment]
> You can already search for a specific base by searching for its name, [example](https://www.pathofexile.com/trade/search/Harvest/NppWT0)
> 
> I don't know if it's what you're looking for ?

That's not enough when you're dealing with Staff vs Warstaff (there are 13 staff bases and 9 warstaff bases). The trouble is you can only do category "Any Staff" which includes all 13+9 bases or "Warstaff" which is the 9 Warstaff bases, I'm looking for the 13 non-warstaff bases.

**Comment by pboutin** [comment]
Sadly, the real solution here would be for GGG to include these categories (non-warstaff) into the existing category option. 

The extension cannot control _how_ items are searched, it can only manipulate the results. Hiding "blacklisted" stuff as they arrive would mess up the pagination and could cause some issues.
