### ISSUE TITLE
Add an "archive" option to folders

### ISSUE THREAD

**Issue by AbeLincoln** [exile-center/better-trading#70]
As a user who does not want to manually manage their "exported" folders when switching builds, it would be nice if the extension could do this for me.  This would allow me to have only relevant folders and queries around, which would help with performance of the extension.

The archive feature could take the output of the Folder Export option and store that in an _Archived_ tab.
- After being archived, the folder would be deleted from the _Bookmarks_ tab.
- From the _Archived_ tab, a user could Delete, Restore, or Export the folder.
  - Deleting would permanently delete the folder, after giving a warning dialog.
  - Restoring would use the internal Import option to create the Folder in the _Bookmarks_ tab again.
  - After being Restored, the Folder would be deleted from the _Archived_ tab.
  - Exporting the folder would have identical behavior to the Export option from the _Bookmarks_ tab.
- The _Archived_ tab would not show the contents of the Folders, just the name (and perhaps the icon).

**Comment by pboutin** [comment]
Performances-wise, I think the rendering is the principal issue while having a lot of folders. The archive feature could simply toggle a flag on the folder. Then we would only need a button to switch between "view the archive" and "view the regular folders".

There's a few things that I'd like to change about how bookmarks are stored, will keep that one in mind.

**Comment by dbjorge** [comment]
This was already implemented in #75 and released some time ago
