### ISSUE TITLE
Make bookmark URL ediatable 

### ISSUE THREAD

**Issue by Smeagol001** [exile-center/better-trading#72]
it would be really cool if you could somehow make it that the serarchespart "/leaugename/" could be easily edited so you can reuse old saved searches w/o redoing all the things.
if this is possible it would be another huge QoL for the trade site

**Comment by pboutin** [comment]
the league name is actually not stored at all in your bookmarks. they dynamically adapt according to the "active" league of the trade site. you can try switching the trade site to "standard" and notice how your bookmarks works for standard as well :)

**Comment by Smeagol001** [comment]
oh cool  i didnt try that so basically youre just storing the searchstring i guess
