### ISSUE TITLE
Copy to PoB

### ISSUE THREAD

**Issue by smblee** [exile-center/better-trading#73]
Would be nice to have another button that will copy as PoB format that i can just paste into PoB items.

**Comment by pboutin** [comment]
Fun fact, I had the exact same idea, almost finished implementing it when a friend pointed to me that the trade site already had this feature natively.

Here it is:
![Screen Shot 2020-11-03 at 8 03 44 AM](https://user-images.githubusercontent.com/4255460/97988595-33c39180-1dab-11eb-8e1c-567c5678e136.png)
