### ISSUE TITLE
big white box

### ISSUE THREAD

**Issue by renzixs** [exile-center/better-trading#77]
hi

can you please put a switch to turn off the white box that appear around the item name in pathofexile.com/trade it really is too bright and the rare items have low visibility. 

[like this](https://user-images.githubusercontent.com/78633781/107156295-97eb8800-698e-11eb-9182-b52308cab8a5.png)

love the tool 
thank you very much

**Comment by pboutin** [comment]
This white box is not intended and I dont see this on my end, can you provide more info ?

- Trade link where you're seeing this
- Browser version
- Extension version (by clicking on the "info" button)

I suspect another extension is causing this glitch, but I'd like to make sure.

**Comment by renzixs** [comment]
yes its on my end im so sorry,

my browser is opera GX which involve a BETA dark mode to all pages and it was fine but when i used the better trading tool it was all white so i had to exclude the trade site from the dark mode and its running super smooth now.

extension ver 1.4.0
thanks alot for the tool and sorry for the trouble

**Comment by pboutin** [comment]
Glad we found the error, thanks for the kind words :)
