### ISSUE TITLE
Undeletable last item

### ISSUE THREAD

**Issue by cosmin-varlan** [exile-center/better-trading#78]
The option "delete" for the last item of the last folder is rendered outside the browser window and cannot be accessed  (probably you have something like overflow: hidden and is displayed outside the window). Adding some space (or some infos) at the end might solve this.
![bug](https://user-images.githubusercontent.com/18011337/107140815-58d91a80-692d-11eb-836a-c4baf5299df2.png)

**Comment by pboutin** [comment]
Thanks for the issue, will look at it for the next release :)
