### ISSUE TITLE
Can NOT export code?

### ISSUE THREAD

**Issue by shao222** [exile-center/better-trading#79]
I found the bug, export code was empty. 
![image](https://user-images.githubusercontent.com/1249351/110728929-bfe03c80-8215-11eb-85af-51768de81df8.png)

So. What can I do?

Thanks. :)

**Comment by pboutin** [comment]
Cannot reproduce on my end, maybe there are some special character into your folder ?
Is there an error in the console when you try this ?
Last question: can you post a screenshot of said folder ?

**Comment by shao222** [comment]
OK, I found out the problem, because i have a translate extension. 
Just now, It's working after I disable the extension.

Thank you. :P
