### ISSUE TITLE
Open all tabsin a folder by clicking on a folder

### ISSUE THREAD

**Issue by mafima** [exile-center/better-trading#86]
Click on folder = opens all tabs

example: 1 click for 3 trade tabs to open

![image](https://user-images.githubusercontent.com/3407209/120779241-2c25c000-c527-11eb-933e-c10a140bb491.png)

**Comment by pboutin** [comment]
Already had this idea in the past, but once a folder gets many items, it starts to bug.

Pro-tip: you can middle click an item to quickly open it in a new tab.
