### ISSUE TITLE
Export is not working with Emojis in names

### ISSUE THREAD

**Issue by kamilrogo** [exile-center/better-trading#88]
Hi. I tried to organize my bookmarks a bit with emojis (since there are no subfolders/separators) but I can't export folder that have Emojis - ther is no "export code" and I can see error in js console :)

To replicate just create folder, add some bookmark and in "name" of the bookmark add any emoji (on Win10 "Win"+".")
samples: 🔵🟢🟠🟨🔺🔃⏫⏪

![error](https://user-images.githubusercontent.com/27273043/123341993-3435b600-d54f-11eb-91a1-3e5d35d282d6.png)

EDIT:

It looks like changing 2 things fixes it:

fix Export:
(change this) btoa(JSON.stringify(payload));
(to this) btoa(escape(JSON.stringify(payload)));

then import need some fixing:
(change this) JSON.parse(atob(serializedFolder));
(to this) JSON.parse(unescape(atob(serializedFolder)));

(tested those changes in dev-tools "Sources")
It looks like previously created "codes" (like without emojis) still works after those changes.

**Comment by pboutin** [comment]
Thanks for taking time to investigate too, will make sure to include it next time I release.

**Comment by dbjorge** [comment]
Thanks for reporting the issue, @kamilrogo ! The fix for this will be released in the upcoming 1.6.0 version.
