### ISSUE TITLE
Allow the disabling of item grouping on unique item searches

### ISSUE THREAD

**Issue by Rosemary102** [exile-center/better-trading#89]
Trying to find items where you need a stat at a specific threshold, only to have uniques clumped together since the same person is selling multiple copies of that unique with different rolls, is very infuriating.

Have it not clump together results if you're searching for a particular roll on an item and that stat is different between the items being group as one. Or if nothing else, at least make the "similar results" button more prominent, since I was scrolling through my  extensions and their options for a while to see why I was being told there were 5 results but only seeing 3 on screen before I noticed the button hiding the items away, in line with the whisper/pm/report buttons and in the same aesthetic as the rest of them so as to not stand out in the slightest.

**Comment by pboutin** [comment]
Once I find the time to release the next release, you will be able to disable this feature if it is annoying to you.

![image](https://user-images.githubusercontent.com/4255460/127520684-6600dfb5-8a60-4c66-b4b2-84e4c6fad984.png)
