### ISSUE TITLE
[Request] Add tilda "~" on mod search

### ISSUE THREAD

**Issue by quanton-dev** [exile-center/better-trading#92]
Adding tilda "~" on trade search would be good. this can be made as toggle option. It would make it superb

**Comment by pboutin** [comment]
I don't see how that one could be done, and I've wanted it for a long time. The trade site doesn't use regular `<select>`, they rely on 100% custom components that are driven by their own app. My extension, from the scope where its running, wouldn't have access to this kind of stuff.
